# shared_v2_0.yaml - Chain-level infrastructure configuration
# This file defines global resources that can be shared across multiple models

config_type: "shared"
config_version: "v2.0"
chain: "avalanche"
description: "Shared database for Avalanche indexers - V2 with pricing service support"

# Data Sources
sources:
  - name: "quicknode-blub"
    path: "streams/quicknode/blub/"
    format: "avalanche-mainnet_block_with_receipts_{:012d}-{:012d}.json"
    source_type: "quicknode_stream"
    description: "QuickNode stream for BLUB transfers"

# Global Token Configs
global_tokens:
  - address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    symbol: "WAVAX"
    name: "Wrapped AVAX"
    decimals: 18
    project: "Avax"
    type: "token"
    description: "Wrapped AVAX token"

  - address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    symbol: "BLUB"
    name: "Blub Token"
    decimals: 18
    project: "Blub"
    type: "token"
    description: "BLUB token"

  - address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    type: "lp_receipt"
    symbol: "JLP"
    name: "Joe LP Token"
    decimals: 18
    project: "LFJ"
    description: "Joe V1 AMM LP Receipt Token"

  - address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    type: "lp_receipt"
    symbol: "LBT"
    name: "LB Token"
    decimals: 18
    project: "LFJ"
    description: "Joe V2 Liquidity Book LP Receipt Token"

  - address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    type: "lp_receipt"
    symbol: "PLP"
    name: "Pharaoh LP Token"
    decimals: 18
    project: "Pharaoh"
    description: "Pharaoh V1 AMM LP Receipt Token"

  - address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    type: "lp_receipt"
    symbol: "LP0"
    name: "DWS LP Token"
    decimals: 18
    project: "DWS"
    description: "DWS Launch AMM LP Receipt Token"

# Contract Configs
contracts:
  - address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    name: "BLUB"
    project: "Blub"
    type: "token"
    description: "BLUB native token contract"
    abi:
      dir: "tokens"
      file: "blub.json"
    transformer:
      name: "TokenTransformer"
      config: {}
    pricing_strategy_default: "global"
    base_token_address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    pricing_start_block: null
    pricing_end_block: null
    status: "active"

  - address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    name: "WAVAX"
    project: "Avax"
    type: "token"
    description: "Wrapped AVAX token contract"
    abi:
      dir: "tokens"
      file: "wavax.json"
    transformer:
      name: "TokenTransformer"
      config: {}
    pricing_strategy_default: "global"
    base_token_address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    pricing_start_block: null
    pricing_end_block: null
    status: "active"

  - address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    name: "JLP:BLUB-AVAX"
    project: "LFJ"
    type: "pool"
    description: "Joe V1 AMM BLUB-AVAX pool"
    abi:
      dir: "pools"
      file: "joe_v1_pool.json"
    transformer:
      name: "JoeV1PoolTransformer"
      config: {}
    pricing_strategy_default: "direct_avax"
    base_token_address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    pricing_start_block: 58220057
    pricing_end_block: null
    status: "active"

  - address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    name: "LB:BLUB-AVAX"
    project: "LFJ"
    type: "pool"
    description: "Joe V2 Liquidity Book BLUB-AVAX pool"
    abi:
      dir: "pools"
      file: "joe_v2_pool.json"
    transformer:
      name: "JoeV2PoolTransformer"
      config: {}
    pricing_strategy_default: "direct_avax"
    base_token_address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    pricing_start_block: 58220057
    pricing_end_block: null
    status: "active"

  - address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    name: "PLP:BLUB-AVAX"
    project: "Pharaoh"
    type: "pool"
    description: "Pharaoh V1 AMM BLUB-AVAX pool"
    abi:
      dir: "pools"
      file: "pharaoh_pool.json"
    transformer:
      name: "PharaohPoolTransformer"
      config: {}
    pricing_strategy_default: "direct_avax"
    base_token_address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    pricing_start_block: 58220057
    pricing_end_block: null
    status: "active"

  - address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    name: "LP0:BLUB-AVAX"
    project: "DWS"
    type: "pool"
    description: "DWS Launch AMM BLUB-AVAX pool"
    abi:
      dir: "pools"
      file: "dws_pool.json"
    transformer:
      name: "DWSPoolTransformer"
      config: {}
    pricing_strategy_default: "direct_avax"
    base_token_address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    pricing_start_block: 58220057
    pricing_end_block: null
    status: "active"

  - address: "0x3fc41c1ae339322ab87b6ba48e30781d88a304d4"
    name: "PCL:BLUB-AVAX"
    project: "PLACEHOLDER"
    type: "pool"
    description: "PLACEHOLDER - Add actual project and details"
    abi:
      dir: "pools"
      file: "placeholder_pool.json"
    transformer:
      name: "PlaceholderPoolTransformer"
      config: {}
    pricing_strategy_default: "direct_avax"
    base_token_address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    pricing_start_block: 58220057
    pricing_end_block: null
    status: "active"

  - address: "0x45a62b090df48243f12a21897e7ed91863e2c86b"
    name: "LFJ Aggregator"
    project: "LFJ"
    type: "router"
    description: "Liquidity Finance Joe aggregator router"
    abi:
      dir: "routers"
      file: "lfj_aggregator.json"
    transformer:
      name: "LFJAggregatorTransformer"
      config: {}
    pricing_strategy_default: "global"
    base_token_address: null
    pricing_start_block: null
    pricing_end_block: null
    status: "active"

  - address: "0x88de50b233052e4fb783d4f6db78cc34fea3e9fc"
    name: "Odos Aggregator"
    project: "Odos"
    type: "router"
    description: "Odos aggregator router"
    abi:
      dir: "routers"
      file: "odos_aggregator.json"
    transformer:
      name: "OdosAggregatorTransformer"
      config: {}
    pricing_strategy_default: "global"
    base_token_address: null
    pricing_start_block: null
    pricing_end_block: null
    status: "active"

  - address: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
    name: "Kyber Aggregator"
    project: "Kyber"
    type: "router"
    description: "Kyber aggregator router"
    abi:
      dir: "routers"
      file: "kyber_aggregator.json"
    transformer:
      name: "KyberAggregatorTransformer"
      config: {}
    pricing_strategy_default: "global"
    base_token_address: null
    pricing_start_block: null
    pricing_end_block: null
    status: "active"

# Address Configs
addresses:
  - address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    name: "BLUB Token"
    type: "token"
    project: "Blub"
    description: "BLUB native token contract"
    grouping: "tokens"
    status: "active"