


# Address Configs
addresses:





  - address: "0xb35033d71cf5e13cab5eb8618260f94363dff9cf"
    name: "RouterLogic"
    type: "agg_logic"
    project: "LFJ"
    description: "LFJ Aggregator Router Logic"
    status: "active"

  - address: "0xb0787776ff90881cec3a0b8e3e91973e6183c146"
    name: "ForwarderLogic"
    type: "agg_logic"
    project: "LFJ"
    description: "LFJ Aggregator Forwarder Logic"
    status: "active"