# config/yaml/config_0.yaml

model:
  id: "blub_test_v2"
  name: "blub_test"
  version: "v2"
  network: "avalanche"
  shared_db: "shared_0"
  model_db: "blub_test_v2"
  description: "Indexer development model: BLUB"
  model_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"


sources:
  - name: "quicknode-blub"
    path: "streams/quicknode/blub/"
    format: "avalanche-mainnet_block_with_receipts_{:012d}-{:012d}.json"
    source_type: "quicknode_stream"
    description: "QuickNode stream for BLUB transfers"


addresses:
  - address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    name: "WAVAX"
    project: "Avax"
    description: "Wrapped AVAX token contract"
    type: "contract"
    subtype: "token_wrapper"

  - address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    name: "BLUB"
    project: "Blub"
    description: "BLUB token contract"
    type: "contract"
    subtype: "token"

  - address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    name: "JLP:BLUB-AVAX"
    project: "LFJ"
    description: "Joe V1 AMM: BLUB-AVAX"
    type: "contract"
    subtype: "pool"

  - address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    name: "LB:BLUB-AVAX"
    project: "LFJ"
    description: "Joe V2 Liquidity Book: BLUB-AVAX"
    type: "contract"
    subtype: "pool"

  - address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    name: "PLP:BLUB-AVAX"
    project: "Pharaoh"
    description: "Pharaoh V1 AMM: BLUB-AVAX"
    type: "contract"
    subtype: "pool"

  - address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    name: "LP0:BLUB-AVAX"
    project: "Unknown"
    description: "Unknown AMM: BLUB-AVAX"
    type: "contract"
    subtype: "pool"

  - address: "0x3fc41c1ae339322ab87b6ba48e30781d88a304d4"
    name: "PCL:BLUB-AVAX"
    project: "Pharaoh"
    description: "Pharaoh V2 CL: BLUB-AVAX"
    type: "contract"
    subtype: "pool"

  - address: "0x45a62b090df48243f12a21897e7ed91863e2c86b"
    name: "AggregatorV2"
    project: "LFJ"
    description: "LFJ Aggregator V2"
    type: "contract"
    subtype: "aggregator"

  - address: "0x88de50b233052e4fb783d4f6db78cc34fea3e9fc"
    name: "RouterV2"
    project: "Odos"
    description: "Odos Aggregator V2"
    type: "contract"
    subtype: "aggregator"

  - address: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
    name: "MetaAggRouter2"
    project: "Kyber"
    description: "Kyber Meta Aggregator V2"
    type: "contract"
    subtype: "aggregator"

  - address: "0xe8afa8eb383ced1696c2d8ceb080f47df48f11af"
    name: "Blub Treasury"
    project: "Blub"
    description: "Blub treasury wallet"
    type: "eoa"
    subtype: "multisig"

  - address: "0x60ae616a2155ee3d9a68541ba4544862310933d4"
    name: "JoeRouter02"
    project: "LFJ"
    description: "TraderJoe V2 Router"
    type: "contract"
    subtype: "router"

  - address: "0x18556da13313f3532c54711497a8fedac273220e"
    name: "LBRouterV2.2"
    project: "LFJ"
    description: "Liquidity Book Router"
    type: "contract"
    subtype: "router"

  - address: "0xaaa45c8f5ef92a000a121d102f4e89278a711faa"
    name: "V1Router"
    project: "Pharaoh"
    description: "Pharaoh V1 Router"
    type: "contract"
    subtype: "router"

  - address: "0x38575264810371c15f0e5744fa2ab29cdef7245d"
    name: "DexRouter"
    project: "OKX"
    description: "OKX DEX Router"
    type: "contract"
    subtype: "router"

  - address: "0xb35033d71cf5e13cab5eb8618260f94363dff9cf"
    name: "RouterLogic"
    project: "LFJ"
    description: "LFJ Aggregator Router Logic"
    type: "contract"
    subtype: "logic"

  - address: "0xb0787776ff90881cec3a0b8e3e91973e6183c146"
    name: "ForwarderLogic"
    project: "LFJ"
    description: "LFJ Aggregator Forwarder Logic"
    type: "contract"
    subtype: "logic"


contracts:
  - address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    block_created: 820
    abi_dir: "tokens"
    abi_file: "wavax.json"
    transformer: "WavaxTransformer"
    transform_init:
      contract: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"

  - address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    block_created: 58219691
    abi_dir: "tokens"
    abi_file: "blub.json"
    transformer: "TokenTransformer"
    transform_init:
      contract: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"

  - address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    block_created: 58220057
    abi_dir: "pools"
    abi_file: "joepair.json"
    transformer: "LfjPoolTransformer"
    transform_init:
        contract: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
        token0: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        token1: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
        base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        fee_collector: "0x60233142befce7d4ed73e7793ead2d6190fccaab"

  - address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    block_created: 58220284
    abi_dir: "pools"
    abi_file: "lbpair.json"
    transformer: "LbPairTransformer"
    transform_init:
        contract: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
        token_x: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        token_y: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
        base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"

  - address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    block_created: 58220990
    abi_dir: "pools"
    abi_file: "pair.json"
    transformer: "PharPairTransformer"
    transform_init:
        contract: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
        token0: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        token1: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
        base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"

  - address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    block_created: 58299144
    abi_dir: "pools"
    abi_file: "joepair.json"
    transformer: "LfjPoolTransformer"
    transform_init:
        contract: "0x819fe65a885d40493f4b91e8a10e242018758432"
        token0: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        token1: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
        base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        fee_collector: "0x60233142befce7d4ed73e7793ead2d6190fccaab"

  - address: "0x3fc41c1ae339322ab87b6ba48e30781d88a304d4"
    block_created: 58220991
    abi_dir: "pools"
    abi_file: "clpool.json"
    transformer: "PharClPoolTransformer"
    transform_init:
        contract: "0x3fc41c1ae339322ab87b6ba48e30781d88a304d4"
        token0: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
        token1: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
        base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"

  - address: "0x45a62b090df48243f12a21897e7ed91863e2c86b"
    block_created: 55299583
    abi_dir: "aggregators"
    abi_file: "lfj_agg.json"
    transformer: "LfjAggregatorTransformer"
    transform_init:
        contract: "0x45a62b090df48243f12a21897e7ed91863e2c86b"

  - address: "0x88de50b233052e4fb783d4f6db78cc34fea3e9fc"
    block_created: 32536584
    abi_dir: "aggregators"
    abi_file: "odos_agg.json"
    transformer: "OdosAggregatorTransformer"
    transform_init:
        contract: "0x88de50b233052e4fb783d4f6db78cc34fea3e9fc"

  - address: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"
    block_created: 24458137
    abi_dir: "aggregators"
    abi_file: "kyber_agg.json"
    transformer: "KyberAggregatorTransformer"
    transform_init:
        contract: "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"


pools:
  - address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    quote_token: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    pricing_default: "direct_avax"

  - address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    quote_token: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    pricing_default: "direct_avax"

  - address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    quote_token: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    pricing_default: "direct_avax"

  - address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    quote_token: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    pricing_default: "direct_avax"

  - address: "0x3fc41c1ae339322ab87b6ba48e30781d88a304d4"
    base_token: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    quote_token: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    pricing_default: "direct_avax"


pricing:
  - model_id: "blub_test_v2"
    pool_address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    pricing_method: "direct_avax"
    price_feed: true
    pricing_start: 58220057

  - model_id: "blub_test_v2"
    pool_address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    pricing_method: "direct_avax"
    price_feed: true
    pricing_start: 58220284

  - model_id: "blub_test_v2"
    pool_address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    pricing_method: "direct_avax"
    price_feed: true
    pricing_start: 58220990

  - model_id: "blub_test_v2"
    pool_address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    pricing_method: "direct_avax"
    price_feed: false
    pricing_start: 58299144

  - model_id: "blub_test_v2"
    pool_address: "0x3fc41c1ae339322ab87b6ba48e30781d88a304d4"
    pricing_method: "direct_avax"
    price_feed: true
    pricing_start: 58220991


tokens:
  - address: "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    symbol: "BLUB"
    decimals: 18

  - address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    symbol: "WAVAX"
    decimals: 18

  - address: "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    symbol: "JLP"
    decimals: 18

  - address: "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    symbol: "LBT"
    decimals: 18

  - address: "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    symbol: "PLP"
    decimals: 18

  - address: "0x819fe65a885d40493f4b91e8a10e242018758432"
    symbol: "LP0"
    decimals: 18


labels:


model-contracts:
  - model_id: "blub_test_v2"
    contracts:
    - "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    - "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
    - "0x39888258d60fed9228f89e13eb57a92f1fa832eb"
    - "0xcb4c6fdcfb7d868df5f1e3d0018438205b243fd6"
    - "0xa87866ba0d82155d0ff36ad06e555aebc98595ca"
    - "0x819fe65a885d40493f4b91e8a10e242018758432"
    - "0x45a62b090df48243f12a21897e7ed91863e2c86b"
    - "0x88de50b233052e4fb783d4f6db78cc34fea3e9fc"
    - "0x6131b5fae19ea4f9d964eac0408e4408b66337b5"

model-tokens:
  - model_id: "blub_test_v2"
    tokens:
    - "0x0f669808d88b2b0b3d23214dcd2a1cc6a8b1b5cd"
    - "0x39888258d60fed9228f89e13eb57a92f1fa832eb"

model-sources:
  - model_id: "blub_test_v2"
    sources:
    - "quicknode-blub"
