"""Add format field to sources table

Revision ID: f32508ad3f12
Revises: 69e567bdcfce
Create Date: 2025-07-16 12:23:41.765553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32508ad3f12'
down_revision = '69e567bdcfce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_price_vwap_time_desc'), table_name='price_vwap')
    op.create_index('idx_price_vwap_time_desc', 'price_vwap', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.add_column('sources', sa.Column('format', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'format')
    op.drop_index('idx_price_vwap_time_desc', table_name='price_vwap', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index(op.f('idx_price_vwap_time_desc'), 'price_vwap', [sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###
